name: cnn-emnist
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy>=1.23,<2
      - opencv-python>=4.8,<5
      - pillow>=9.5,<11
      - pyqt5>=5.15,<6
      - tensorflow>=2.11,<2.16
